title: "Amol Prakash"
logo: assets/headshot_circle.png
description: "Doctor turned Informatician | Data Analyst | Data Scientist"
show_downloads: false
theme: jekyll-theme-minimal

download:
  enabled: false
  title: "Download My Resume"
  files:
    - name: "Resume"
      link: "https://yourgithubusername.github.io/repository-name/resume.pdf"

