name: Generate Isometric Commit Calendar

on:
  schedule: [{ cron: "0 0 * * 1" }] # every Monday
  workflow_dispatch:               # manual run option

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: assets/isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: America/Chicago  # or change to your timezone
