name: Generate Isometric Commit Calendar

on:
  schedule: [{ cron: "0 0 * * 1" }] # every Monday
  workflow_dispatch:               # manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: assets/isocalendar.svg    # <-- This MUST match exactly
          token: ${{ secrets.METRICS_TOKEN }} # <-- Token with `repo` scope
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
